# Generated by Django 3.2.3 on 2021-05-27 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HashFil',
            new_name='HashFile',
        ),
    ]
