# Generated by Django 3.2.3 on 2021-05-27 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_rename_hashfil_hashfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashfile',
            name='name',
            field=models.CharField(default='hola', max_length=500),
            preserve_default=False,
        ),
    ]
