# Generated by Django 3.2.3 on 2021-05-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_hashfile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhiteListUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=500, unique=True)),
            ],
        ),
    ]
