# Generated by Django 3.2.3 on 2021-05-29 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_alarmlog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrevetionLogAlarm',
            new_name='PrevetionLogDirectory',
        ),
    ]
