# Generated by Django 3.2.3 on 2021-05-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_promiscuodirectory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmlog',
            name='reason',
            field=models.TextField(),
        ),
    ]
