# Generated by Django 3.2.3 on 2021-05-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_alter_alarmlog_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarentineDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
            ],
        ),
    ]
