# Generated by Django 3.2.3 on 2021-05-30 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0007_prevetionlog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrevetionLog',
            new_name='PreventionLog',
        ),
    ]
