# Generated by Django 3.2.3 on 2021-06-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0009_securelogdirectory'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLogDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
            ],
        ),
    ]
