# Generated by Django 3.2.3 on 2021-06-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0013_mailqueuelimit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcesConsumeLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveBigIntegerField()),
            ],
        ),
    ]
