# Generated by Django 3.2.3 on 2021-06-18 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0014_procesconsumelimit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProcesConsumeLimit',
            new_name='ProcessConsumeLimit',
        ),
    ]
