# Generated by Django 3.2.4 on 2021-06-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0016_auto_20210618_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
    ]
