# Generated by Django 3.2.4 on 2021-06-19 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0017_scripttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_fail_authentication_alarm', models.PositiveBigIntegerField()),
                ('threshold_fail_authentication_prevention', models.PositiveBigIntegerField()),
            ],
        ),
    ]
