# Generated by Django 3.2.4 on 2021-06-27 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0018_threshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='DDosDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
            ],
        ),
    ]
